import { Inter } from "next/font/google";
import "./admin.css";
import Footer from "@/components/HomePage/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
